### ISSUE TITLE
Question about support and Vue3

### ISSUE THREAD

**Issue by hosnar** [MatthijsBurgh/vue-cli-plugin-electron-builder#54]
Hey. Is there any chance you plan to maintain this codebase, since original one is not maintained anymore? Also, is it possible to use this library with Vue3 (migrate from Vue2 to Vue3)?

Thank you

**Comment by MatthijsBurgh** [comment]
I plan to eventually migrate to Vue3. Though I have no timeline for this. As I use this library for my own applications. I will need to be sure all deps of my applications are Vue3 ready. Only then I will try to migrate my apps and this library to Vue3.

The current version isn't Vue3 ready I think. As the current version uses an older `vue-cli`, which still uses webpack 4. So you can go ahead and try stuff. But I will not provide any Vue3 support for the current release.
